# Generated by Django 4.2.3 on 2023-07-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
